name: Build and Deploy to Docker Hub

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag r0913387/touristattractions

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.r0913387 }}
        password: ${{ secrets.Zcana6867 }}

    - name: Push the Docker image
      run: docker push r0913387/touristattractions
